services:
  proxy:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - $PWD/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  web:
    image: httpd
    volumes:
      - $PWD/httpd/docs:/usr/local/apache2/htdocs
